### ISSUE TITLE
About the list of IP addresses and Service Tag used by Azure Container Apps

### ISSUE THREAD

**Issue by YuKogasaka** [microsoft/azure-container-apps#192]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I checked the information on the following Microsoft Download Center site about the public IP address and Service Tag used for sending/receiving from Azure Container Apps without custom VNet, but I could not find it.

- Download Azure IP Ranges and Service Tags – Public Cloud from Official Microsoft Download Center  
https://www.microsoft.com/en-us/download/details.aspx?id=56519

Are there any plans to release it in the future?

This is because I want to restrict access sources with the firewall on the client side.

**Comment by kendallroden** [comment]
Yes we will be releasing a doc update with these details in the meantime: https://github.com/microsoft/azure-container-apps/wiki/Lock-down-VNET-with-Network-Security-Groups-and-Firewall

**Comment by JennyLawrance** [comment]
@YuKogasaka: We evaluated the use of Service-Tags for outbound data path calls and decided against introducing such a tag. There are multiple technical reasons for this decision. We recommend use of VNET enabled environments for securing connections to external Azure resources.

**Comment by FlorentATo** [comment]
Did something change since this discussion ? I see no Service Tag related to ContainerApps in the [official documentation](https://learn.microsoft.com/en-us/azure/virtual-network/service-tags-overview). However, a Service Tag named "ContainerAppsManagement" is indeed present in the Azure portal:

<img width="586" height="1023" alt="Image" src="https://github.com/user-attachments/assets/907bb5bf-ab1a-4755-9187-8ba667e16604" />

This appears to be undocumented as "ContainerAppsManagement" returns no results on Google.
